name: Publish to CRMM

on:
  release:
    types: [published]

jobs:
  prepare:
    runs-on: ubuntu-latest
    outputs:
      game-version: ${{ steps.extract.outputs.game-version }}
    
    steps:
      - id: extract
        name: Extract game version
        run: echo "game-version=${GITHUB_EVENT_RELEASE_TAG#*-}" >> $GITHUB_OUTPUT
        env:
          GITHUB_EVENT_RELEASE_TAG: ${{ github.event.release.tag_name }}

  publish-to-crmm:
    needs: prepare
    name: Upload version to CRMM
    uses: PuzzlesHQ/Puzzles-Workflows/.github/workflows/upload-version.yml@main
    secrets: inherit
    with:
      project-slug: "RCSwbKUrOaudoth8pg"
      title: ${{ github.event.release.name }}
      changelog: ${{ github.event.release.body }}
      version: ${{ github.event.release.tag_name }}
      loaders: "puzzle_loader"
      game-versions: ${{ needs.prepare.outputs.game-version }}
      primary-file: "build/libs/cosmic-api-${{ github.event.release.tag_name }}-merged-bundle.jar"
